### ISSUE TITLE
Mismatch between GitHub, Git

### ISSUE THREAD

**Issue by wooorm** [ChanelZM/real-time-web#1]
Commits you make on your computer aren’t associated with your GitHub account (resulting in those [broken images](https://github.com/ChanelZM/real-time-web/commits/master)).

Probably fix: https://help.github.com/articles/setting-your-email-in-git/#setting-your-email-address-for-every-repository-on-your-computer.

**Comment by ChanelZM** [comment]
Done!

**Comment by wooorm** [comment]
Yay! 🎉
