### ISSUE TITLE
Fix ESLint fail

### ISSUE THREAD

**Issue by wooorm** [ChanelZM/real-time-web#3]
Currently ESLint fails as it doesn’t recognise `io` as a global. That’s because `io` is injected into the browser by another script.

In this case, as it’s intentional, you can make ESLint [recognise `io` as a global](http://eslint.org/docs/user-guide/configuring#specifying-globals) like so:

```js
/* global io */
```

**Comment by ChanelZM** [comment]
Fixed in commit 78fe691
